# Generated by Django 5.2.5 on 2025-08-20 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('noc', 'NOC'), ('engredes', 'Engenharia de Redes'), ('admin', 'Administrador')], default='noc', max_length=10),
        ),
    ]
