# Generated by Django 5.2.5 on 2026-01-16 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listas', '0001_initial'),
        ('solicitantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BLOQUEIO', 'Bloqueio'), ('DESBLOQUEIO', 'Desbloqueio')], default='BLOQUEIO', max_length=20)),
                ('nome', models.CharField(blank=True, max_length=255)),
                ('data_prevista', models.DateTimeField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='listas.lista')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitantes.solicitante')),
            ],
        ),
    ]
