# Generated by Django 5.2.5 on 2026-02-02 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitacao',
            old_name='data_prevista',
            new_name='data_prevista_desbloqueio',
        ),
    ]
