# Generated by Django 5.2.5 on 2025-08-25 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='enderecos',
            field=models.ManyToManyField(blank=True, related_name='solicitacoes', to='enderecos.endereco'),
        ),
    ]
