# Generated by Django 5.2.5 on 2025-08-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_solicitacao_enderecos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='enderecos',
        ),
    ]
