# Generated by Django 5.2.5 on 2026-02-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0002_rename_data_prevista_solicitacao_data_prevista_desbloqueio'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitacao',
            name='data_prevista_renovacao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
