# Generated by Django 5.2.5 on 2025-08-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0003_remove_solicitacao_enderecos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='status',
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='nome',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
