# Generated by Django 5.2.5 on 2026-01-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0004_remove_solicitacao_status_solicitacao_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitacao',
            name='data_execucao',
        ),
    ]
