# Generated by Django 5.2.5 on 2026-01-16 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('ipv4', 'IPv4'), ('ipv6', 'IPv6'), ('url', 'URL')], editable=False, max_length=10)),
                ('status', models.CharField(choices=[('bloqueado', 'Bloqueado'), ('desbloqueado', 'Desbloqueado'), ('excluido', 'Excluído')], default='desbloqueado', max_length=20)),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_desbloqueio', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
