# Generated by Django 5.2.5 on 2026-01-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='data_ultima_solicitacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da última solicitação'),
        ),
    ]
