# Generated by Django 5.2.5 on 2025-08-21 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('listas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='data_desbloqueio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='endereco',
            name='lista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enderecos', to='listas.lista'),
        ),
    ]
