# Generated by Django 5.2.5 on 2026-02-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_endereco_data_ultima_solicitacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='data_renovacao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
