# Generated by Django 5.2.5 on 2025-08-22 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='lista',
        ),
    ]
