# Generated by Django 5.2.5 on 2026-01-16 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enderecos', '0001_initial'),
        ('solicitantes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('data_prevista_desbloqueio', models.DateTimeField(blank=True, null=True)),
                ('criador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('enderecos', models.ManyToManyField(blank=True, related_name='listas', to='enderecos.endereco')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='solicitantes.solicitante')),
            ],
        ),
    ]
