# Generated by Django 5.2.5 on 2025-08-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0003_remove_endereco_lista'),
        ('listas', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='enderecos',
            field=models.ManyToManyField(blank=True, related_name='listas', to='enderecos.endereco'),
        ),
    ]
